pom.xml, src/test/java/page/LoginPage.java, src/test/java/runner/BaseTest.java, src/test/java/runner/BrowserFactory.java, src/test/java/runner/PlaywrightOptions.java, src/test/java/runner/ProjectProperties.java, src/test/java/runner/ProjectUtils.java, src/test/resources/log4j2.xml
Логирование для фреймворка и упрощена логика работы с артефактами.
=> [+] add-log4j logging to framework

.github/workflows/cancel.yml, .github/workflows/ci.yml, .github/workflows/notify.yml, .gitignore, README.md, checkstyle-suppressions.xml, mod_v10.17.0_google_checks.xml, pom.xml, src/test/java/LoginPageTest.java, src/test/java/runner/BaseTest.java, src/test/java/runner/PlaywrightOptions.java, src/test/java/runner/ProjectProperties.java, src/test/java/runner/ProjectUtils.java, src/test/resources/allure.properties, suite/chrome-smoke-parallel.xml, suite/chrome-smoke.xml
Исправил названия класса и добавил debug режим запуска mvn
=> [!] fix class name typo

.github/workflows/ci.yml, README.md
=> [!] add one more debug command line

.github/workflows/ci.yml, .gitignore, README.md
Переписал под GitHub Actions - нуждается в дальнейшей настройке
=> [+] CI deploy using GitHub Actions

src/test/java/LoginPageTest.java, src/test/java/page/LoginPage.java
[+] testRememberMeUncheckedDontSaveUserEmail
=> [ATC_00.001.01] User email is not remembered after first successful login

pom.xml
=> Feat: add allure-maven plugin for allure testing

src/test/java/xyz/npgw/test/common/ProjectUtils.java, src/test/java/xyz/npgw/test/common/base/BaseTest.java, src/test/java/xyz/npgw/test/tests/TransactionsPageTest.java
=> Feature: add autologin for all test classes excluding LoginPageTest

src/test/java/xyz/npgw/test/common/ProjectProperties.java, src/test/java/xyz/npgw/test/common/base/BaseTest.java
=> Fix: change artefact upload to allure, clean logging and add nullchecks to have a clean allure report

src/test/java/xyz/npgw/test/common/Constants.java, src/test/java/xyz/npgw/test/page/LoginPage.java, src/test/java/xyz/npgw/test/run/DashboardPageTest.java, src/test/java/xyz/npgw/test/run/LoginPageTest.java, src/test/java/xyz/npgw/test/run/TransactionsPageTest.java
close #150 
close #151 
fix #108
=> Feature: add #150 and #151 ATC

src/test/java/xyz/npgw/test/page/SaAcquirersTab.java, src/test/java/xyz/npgw/test/run/SaAcquirersTabTest.java
=> renaming-locator-and-methods SaAcquirersTab

src/test/java/xyz/npgw/test/page/SaAcquirersTab.java, src/test/java/xyz/npgw/test/page/base/BasePage.java, src/test/java/xyz/npgw/test/run/SaAcquirersTabTest.java
https://github.com/NPGW/npgw-ui-test/issues/157
=> ATC 11.000.02 Verify: The visibility of the 'Acquirers List' header, which contains a list of Acquirers.

src/test/java/xyz/npgw/test/run/SaAcquirersTabTest.java
=> fix-refact

src/test/java/xyz/npgw/test/common/ProjectUtils.java, src/test/java/xyz/npgw/test/common/UserRole.java, src/test/java/xyz/npgw/test/common/base/BaseTest.java, src/test/java/xyz/npgw/test/page/AboutBlankPage.java, src/test/java/xyz/npgw/test/page/base/BasePageWithHeader.java, src/test/java/xyz/npgw/test/run/LoginPageTest.java
use:
```
public void testName(@Optional("GUEST") String userRole) {
}
```
Default role is SUPER - even if no parameter is used
Available roles USER, ADMIN, GUEST(will not login to site before test)
=> Feature: add user role

src/test/java/xyz/npgw/test/page/TransactionsPage.java, src/test/java/xyz/npgw/test/page/base/BasePage.java, src/test/java/xyz/npgw/test/run/TransactionsPageTest.java
=> [ATC-06.013.00] Verify the visibility of the control panel elements on the Transactions Page

pom.xml, src/test/java/xyz/npgw/test/common/ProjectProperties.java, src/test/java/xyz/npgw/test/common/base/BaseTest.java, src/test/java/xyz/npgw/test/page/AddCompanyDialog.java, src/test/java/xyz/npgw/test/page/LoginPage.java, src/test/java/xyz/npgw/test/page/TransactionsPage.java, src/test/java/xyz/npgw/test/page/base/SystemAdministrationWithTableBasePage.java, src/test/java/xyz/npgw/test/page/systemadministration/AcquirersPage.java, src/test/java/xyz/npgw/test/page/systemadministration/CompaniesAndBusinessUnitsPage.java
Add lombok to pom.xml
useful annotations:
@Log4j2
@Setter
@Getter
@NoArgsConstructor
@AllArgsConstructor
=> Feature: add lombok

src/test/java/xyz/npgw/test/run/AddCompanyDialogTest.java, src/test/java/xyz/npgw/test/testdata/TestDataProvider.java
=> [ATC_10.002.05] Error is displayed when trying to create a company with special characters in the name.

src/test/java/xyz/npgw/test/common/provider/TestDataProvider.java, src/test/java/xyz/npgw/test/page/systemadministration/AddAcquirerDialog.java, src/test/java/xyz/npgw/test/run/AddAcquirerDialogTest.java
https://github.com/NPGW/npgw-ui-test/issues/255
=> ATC_11.001.01 Verifies that the status radio buttons ('Active' and 'Inactive') toggle correctly.

src/test/java/xyz/npgw/test/common/provider/TestDataProvider.java, src/test/java/xyz/npgw/test/page/systemadministration/CompaniesAndBusinessUnitsPage.java, src/test/java/xyz/npgw/test/run/AddCompanyDialogTest.java, src/test/resources/jsonfiles/company.json
#261 
#246 - assert was added due  bug fixing
=> [ATC_10.002.12] Error message when trying to create a company with invalid length and special characters.

src/test/java/xyz/npgw/test/page/systemadministration/AcquirersPage.java, src/test/java/xyz/npgw/test/run/AcquirersPageTest.java, src/test/java/xyz/npgw/test/run/TransactionsPageTest.java
https://github.com/NPGW/npgw-ui-test/issues/268
=> ATC_11.003.02 Verify that re-selecting an already selected status keeps the selection unchanged.

src/test/java/xyz/npgw/test/component/SystemMenuComponent.java, src/test/java/xyz/npgw/test/page/system/AcquirersPage.java, src/test/java/xyz/npgw/test/page/system/GatewayPage.java, src/test/java/xyz/npgw/test/run/AcquirersPageTest.java, src/test/java/xyz/npgw/test/run/GatewayPageTest.java
ATC_12.002.00: https://github.com/NPGW/npgw-ui-test/issues/283
***
ATC_12.002.02: https://github.com/NPGW/npgw-ui-test/issues/284
BUG: https://github.com/NPGW/npgw-ui-test/issues/282
=> ATC_12.002.00  |  ATC_12.002.02 

src/test/java/xyz/npgw/test/run/EditCompanyDialogTest.java
=> testEditCompanyInfoAndSave  #266 - bug gone

src/test/java/xyz/npgw/test/common/provider/TestDataProvider.java, src/test/java/xyz/npgw/test/page/TransactionsPage.java, src/test/java/xyz/npgw/test/page/common/HeaderComponent.java, src/test/java/xyz/npgw/test/run/TransactionsPageTest.java
=>  [ATC_06.002.01] Filtering transactions by Currency

src/test/java/xyz/npgw/test/page/common/TableComponent.java, src/test/java/xyz/npgw/test/page/dialog/acquirer/AcquirerDialog.java, src/test/java/xyz/npgw/test/page/dialog/acquirer/AddAcquirerDialog.java, src/test/java/xyz/npgw/test/run/AddAcquirerDialogTest.java
https://github.com/NPGW/npgw-ui-test/issues/322
=> add ATC_11.001.02  Country and Timezone field interaction during Acquirer creation

src/test/java/xyz/npgw/test/run/AddAcquirerDialogTest.java, src/test/java/xyz/npgw/test/run/EditAcquirerDialogTest.java
https://github.com/NPGW/npgw-ui-test/issues/326
BR: https://github.com/NPGW/npgw-ui-test/issues/323
=> ATC_11.001.03 Selecting already selected Timezone does not change the value

src/test/java/xyz/npgw/test/page/TransactionsPage.java, src/test/java/xyz/npgw/test/run/TransactionsPageTest.java
=> Error Message By Amount

src/test/java/xyz/npgw/test/page/TransactionsPage.java, src/test/java/xyz/npgw/test/run/EditCompanyDialogTest.java, src/test/java/xyz/npgw/test/run/TeamPageTest.java, src/test/java/xyz/npgw/test/run/TransactionsPageTest.java
=> The Visibility Of The Payment Method Options

src/test/java/xyz/npgw/test/page/common/HeaderComponent.java, src/test/java/xyz/npgw/test/run/EditCompanyDialogTest.java, src/test/java/xyz/npgw/test/run/HeaderComponentTest.java
=> Refactor: Add checking full loading of Logo picture

src/test/java/xyz/npgw/test/run/GatewayPageTest.java
https://github.com/NPGW/npgw-ui-test/issues/307
https://github.com/NPGW/npgw-ui-test/issues/347
=> REF [ATC_12.003.01] System administration > Gateway > Select company > Business units list

src/test/java/xyz/npgw/test/page/system/AcquirersPage.java, src/test/java/xyz/npgw/test/run/AcquirersPageTest.java
[Task to #157] 
System -> 
Acquirers -> 
testVisibilityHeaderAndAcquirersList 
fixing after update
=> System -> Acquirers -> testVisibilityHeaderAndAcquirersList fixing after update

src/test/java/xyz/npgw/test/page/system/AcquirersPage.java, src/test/java/xyz/npgw/test/run/AcquirersPageTest.java
[Task to #134] 
System -> 
Acquirers -> 
testVisibilityAcquirersListControlTab 
fixing after update
=> System -> Acquirers -> testVisibilityAcquirersListControlTab fixing after update

src/test/java/xyz/npgw/test/page/system/AcquirersPage.java, src/test/java/xyz/npgw/test/run/AcquirersPageTest.java
[Task to #268] 
System -> 
Acquirers -> 
testRetainStatusWhenReSelectingSameOption 
fixing after update
=> System -> Acquirers -> testRetainStatusWhenReSelectingSameOption fixing after update

src/test/java/xyz/npgw/test/common/provider/TestDataProvider.java, src/test/java/xyz/npgw/test/common/util/ResponseUtils.java, src/test/java/xyz/npgw/test/page/TransactionsPage.java, src/test/java/xyz/npgw/test/page/common/TableComponent.java, src/test/java/xyz/npgw/test/run/TransactionsPageTest.java
Transactions 
Check/Uncheck Visible columns in the Settings and verify table columnheaders
=> [ATC_06.007.00] Transactions -> Settings -> Check/Uncheck Visible columns in the Settings and verify table columnheaders 

src/test/java/xyz/npgw/test/page/system/AcquirersPage.java, src/test/java/xyz/npgw/test/run/AcquirersPageTest.java, src/test/java/xyz/npgw/test/run/AddCompanyDialogTest.java
https://github.com/NPGW/npgw-ui-test/issues/380
=> [ATC_11.000.03] Verify that the "Rows per page" dropdown has the following options: 10, 25, 50, 100.

src/test/java/xyz/npgw/test/page/system/AcquirersPage.java, src/test/java/xyz/npgw/test/run/AcquirersPageTest.java
https://github.com/NPGW/npgw-ui-test/issues/382
=> [ATC_11.000.04] SA/Aquirer > Verify Selecting "Rows Per Page" Option Updates the Field Value

src/test/java/xyz/npgw/test/run/TransactionsPageTest.java
=> Reset Amount Values

src/test/java/xyz/npgw/test/page/system/AcquirersPage.java, src/test/java/xyz/npgw/test/page/system/CompaniesAndBusinessUnitsPage.java, src/test/java/xyz/npgw/test/run/AcquirersPageTest.java, src/test/java/xyz/npgw/test/run/AddBusinessUnitTest.java, src/test/java/xyz/npgw/test/run/AddCompanyDialogTest.java, src/test/java/xyz/npgw/test/run/TransactionsPageTest.java
[Task to #243,  [#401](https://github.com/NPGW/npgw-ui-test/issues/401)] 
System 
-> Acquirers 
->testFilterAcquirersByStatus 
fixing after update
=> System -> Acquirers ->testFilterAcquirersByStatus fixing after update #401

src/test/java/xyz/npgw/test/run/DashboardPageTest.java
=> [ATC-02.001.00] Dashboard | Error message is displayed when start date is after end date

src/test/java/xyz/npgw/test/common/provider/TestDataProvider.java, src/test/java/xyz/npgw/test/page/base/BaseModel.java, src/test/java/xyz/npgw/test/page/system/AcquirersPage.java, src/test/java/xyz/npgw/test/run/AcquirersPageTest.java
https://github.com/NPGW/npgw-ui-test/issues/385
=> [ATC_11.000.05] Verify Selecting "Rows Per Page" Option Updates the Field Value

src/test/java/xyz/npgw/test/page/dialog/merchant/EditBusinessUnitDialog.java, src/test/java/xyz/npgw/test/page/system/CompaniesAndBusinessUnitsPage.java, src/test/java/xyz/npgw/test/run/EditBusinessUnitDialogTest.java
System administration > Companies and business units > Edit Business Unit
close #387
=> [ATC_10.008.00] Verify 'Edit Business Unit' window header title

.gitignore
add docker-compose*.yml to .gitignore
=> Feature: add docker-compose*.yml

src/test/java/xyz/npgw/test/page/TransactionsPage.java, src/test/java/xyz/npgw/test/run/AddCompanyDialogTest.java, src/test/java/xyz/npgw/test/run/EditBusinessUnitDialogTest.java, src/test/java/xyz/npgw/test/run/TeamPageTest.java, src/test/java/xyz/npgw/test/run/TransactionsPageTest.java
=> [ATC_06.006.00] The presence of the dropdown options export table data to file

src/test/java/xyz/npgw/test/page/common/HeaderComponent.java, src/test/java/xyz/npgw/test/run/EditCompanyDialogTest.java, src/test/java/xyz/npgw/test/run/TransactionsPageTest.java
=> Refactor after update of EditCompanyDialogTest

src/test/java/xyz/npgw/test/common/TestUtils.java, src/test/java/xyz/npgw/test/common/entity/Acquirer.java, src/test/java/xyz/npgw/test/common/entity/SystemConfig.java, src/test/java/xyz/npgw/test/page/dialog/acquirer/AcquirerDialog.java, src/test/java/xyz/npgw/test/page/dialog/acquirer/AddAcquirerDialog.java, src/test/java/xyz/npgw/test/run/AddAcquirerDialogTest.java
https://github.com/NPGW/npgw-ui-test/issues/427
=> [ATC_11.001.005 ] SA > Acquirer > Add Acquirer > Attempt to create an Acquirer with an existing name

src/test/java/xyz/npgw/test/common/Constants.java, src/test/java/xyz/npgw/test/common/provider/TestDataProvider.java, src/test/java/xyz/npgw/test/page/common/HeaderComponent.java, src/test/java/xyz/npgw/test/page/common/SelectCompanyComponent.java, src/test/java/xyz/npgw/test/run/AddCompanyDialogTest.java
Changed endpoint for clickSystemAdministrationLink waiter as a part of fixing
=> Fix ignored tests in AddCompanyTest

src/test/java/xyz/npgw/test/page/common/HeaderComponent.java, src/test/java/xyz/npgw/test/run/HeaderComponentTest.java
[ATC_01.006.02](https://github.com/issues/assigned?issue=NPGW%7Cnpgw-ui-test%7C437)
[ATC_01.006.03](https://github.com/issues/assigned?issue=NPGW%7Cnpgw-ui-test%7C440)
=> [ATC_01.006.02], [ATC_01.006.03] Verify that the user can switch the color theme

src/test/java/xyz/npgw/test/page/system/AcquirersPage.java, src/test/java/xyz/npgw/test/page/system/MenuComponent.java, src/test/java/xyz/npgw/test/run/AcquirersPageTest.java
https://github.com/NPGW/npgw-ui-test/issues/432
=> ATC_11.000.08 Verify Acquirers table contains correct column headers

src/test/java/xyz/npgw/test/run/AddAcquirerDialogTest.java
=> Removed Ignore

src/test/java/xyz/npgw/test/page/system/CompaniesAndBusinessUnitsPage.java, src/test/java/xyz/npgw/test/run/AddBusinessUnitTest.java
AddBusinessUnitTest - fix ignored tests
=> AddBusinessUnitTest - fix ignored tests

src/test/java/xyz/npgw/test/run/EditBusinessUnitDialogTest.java, src/test/java/xyz/npgw/test/run/HeaderTest.java
fix EditBusinessUnitDialogTest after update
rename HeaderComponentTest to HeaderTest
refactor HeaderTest
=> fix EditBusinessUnitDialogTest after update

src/test/java/xyz/npgw/test/page/system/AcquirersPage.java, src/test/java/xyz/npgw/test/run/AcquirersPageTest.java, src/test/java/xyz/npgw/test/run/AddAcquirerDialogTest.java, src/test/java/xyz/npgw/test/run/EditAcquirerDialogTest.java
https://github.com/NPGW/npgw-ui-test/issues/239
https://github.com/NPGW/npgw-ui-test/pull/256
https://github.com/NPGW/npgw-ui-test/issues/460
=> Fix ATC_11.006.00 Was ignored after updating

src/test/java/xyz/npgw/test/page/common/SelectCompanyComponent.java, src/test/java/xyz/npgw/test/page/dialog/user/AddUserDialog.java, src/test/java/xyz/npgw/test/page/dialog/user/UserDialog.java, src/test/java/xyz/npgw/test/page/system/TeamPage.java, src/test/java/xyz/npgw/test/run/AddCompanyDialogTest.java, src/test/java/xyz/npgw/test/run/TeamPageTest.java
=> Fix ignored tests

src/test/java/xyz/npgw/test/common/util/TestUtils.java, src/test/java/xyz/npgw/test/page/DashboardPage.java, src/test/java/xyz/npgw/test/page/base/BaseModel.java, src/test/java/xyz/npgw/test/page/common/TableComponent.java, src/test/java/xyz/npgw/test/page/common/TableTrait.java, src/test/java/xyz/npgw/test/page/dialog/user/ChangeUserActivityDialog.java, src/test/java/xyz/npgw/test/page/system/CompaniesAndBusinessUnitsPage.java, src/test/java/xyz/npgw/test/page/system/TeamPage.java, src/test/java/xyz/npgw/test/run/TeamPageTest.java
=> [ATC_09.007.03] [ATC_09.007.04][ATC_09.007.05] Edit company admin

src/test/java/xyz/npgw/test/common/provider/TestDataProvider.java, src/test/java/xyz/npgw/test/page/TransactionsPage.java, src/test/java/xyz/npgw/test/run/TeamPageTest.java, src/test/java/xyz/npgw/test/run/TransactionsPageTest.java
=> [ATC_06.006.01] Download files: PDF, Excel, CVS

src/test/java/xyz/npgw/test/page/DashboardPage.java, src/test/java/xyz/npgw/test/page/common/AlertComponent.java, src/test/java/xyz/npgw/test/page/common/AlertTrait.java, src/test/java/xyz/npgw/test/page/common/SelectCompanyTrait.java, src/test/java/xyz/npgw/test/page/common/TableTrait.java, src/test/java/xyz/npgw/test/page/system/AcquirersPage.java, src/test/java/xyz/npgw/test/page/system/BaseSystemPage.java, src/test/java/xyz/npgw/test/page/system/CompaniesAndBusinessUnitsPage.java, src/test/java/xyz/npgw/test/page/system/TeamPage.java, src/test/java/xyz/npgw/test/run/AddAcquirerDialogTest.java, src/test/java/xyz/npgw/test/run/AddBusinessUnitTest.java, src/test/java/xyz/npgw/test/run/AddCompanyDialogTest.java, src/test/java/xyz/npgw/test/run/EditCompanyDialogTest.java, src/test/java/xyz/npgw/test/run/TeamPageTest.java
#485 
Поиск любого алерта сохранен, так как он у нас всегда проверяет конкретное сообщение, алерт на  ожидание Success тоже сохранен, так как это как доп проверка, что все норм, название поменяно на случай, если в дальнейшем будем ожидать и на ошибку
=> Refactor alert with AlertTrait и AlertComponent

src/test/java/xyz/npgw/test/common/util/TestUtils.java, src/test/java/xyz/npgw/test/page/dialog/user/UserDialog.java, src/test/java/xyz/npgw/test/page/system/UserTableComponent.java, src/test/java/xyz/npgw/test/run/TeamPageTest.java
Create company analyst close #492
=> [ATC_09.007.06]Create company analyst test

src/test/java/xyz/npgw/test/run/AcquirersPageTest.java
https://github.com/NPGW/npgw-ui-test/pull/489
=> Cleaning Test testColumnHeadersDisplayCorrectlyOnAllPages

.github/workflows/ci.yml, config/testng.xml, pom.xml, src/test/java/xyz/npgw/test/common/ProjectProperties.java, src/test/java/xyz/npgw/test/common/base/BaseTest.java, src/test/java/xyz/npgw/test/common/base/RetryAnalyzer.java, src/test/java/xyz/npgw/test/common/base/RetryListener.java, src/test/java/xyz/npgw/test/page/TransactionsPage.java, src/test/java/xyz/npgw/test/page/common/AlertComponent.java, src/test/java/xyz/npgw/test/page/common/SelectBusinessUnitComponent.java, src/test/java/xyz/npgw/test/page/common/SelectBusinessUnitTrait.java, src/test/java/xyz/npgw/test/page/dialog/user/UserDialog.java, src/test/java/xyz/npgw/test/page/system/TeamPage.java, src/test/java/xyz/npgw/test/run/AcquirersPageTest.java, src/test/java/xyz/npgw/test/run/TeamPageTest.java, src/test/java/xyz/npgw/test/run/TransactionsPageTest.java
add option failFast to abort all further test on first test failure
add retry option to emulate traces&video "on-first-retry" behavior of Playwright
=> Feature: add test run failFast

src/test/java/xyz/npgw/test/common/provider/TestDataProvider.java, src/test/java/xyz/npgw/test/run/AddBusinessUnitTest.java, src/test/java/xyz/npgw/test/run/AddCompanyDialogTest.java
=> Remove duplicating tests

src/test/java/xyz/npgw/test/page/common/SelectBusinessUnitComponent.java, src/test/java/xyz/npgw/test/run/TransactionsPageTest.java
[503](https://github.com/NPGW/npgw-ui-test/issues/503)
=> [ATC_06.001.00] Verify that the Company admin can see all the company's business units in the Business unit dropdown list

src/test/java/xyz/npgw/test/common/provider/TestDataProvider.java, src/test/java/xyz/npgw/test/page/dialog/acquirer/AcquirerDialog.java, src/test/java/xyz/npgw/test/run/AddAcquirerDialogTest.java, src/test/java/xyz/npgw/test/run/EditBusinessUnitDialogTest.java
https://github.com/NPGW/npgw-ui-test/issues/526
=> ATC_11.001.07 Verify that 'Create' button is disabled when Acquirer name is empty.

src/test/java/xyz/npgw/test/page/system/CompaniesAndBusinessUnitsPage.java, src/test/java/xyz/npgw/test/run/EditBusinessUnitDialogTest.java
=> [ATC_10.008.03] System administration > Companies and business units > Edit BU | Verify that the dialog is closed by clicking on the 'Close' button

src/test/java/xyz/npgw/test/page/system/TeamPage.java, src/test/java/xyz/npgw/test/page/system/UserTableComponent.java, src/test/java/xyz/npgw/test/run/TeamPageTest.java
=> [ATC-09.001.01] Team | Status filter correctly displays users with 'Active' or 'Inactive' status

src/test/java/xyz/npgw/test/run/EditBusinessUnitDialogTest.java, src/test/java/xyz/npgw/test/run/TransactionsPageTest.java
=> [ATC_10.008.04] System administration > Companies and business units > Edit BU | Verify that the dialog is closed by clicking on the 'Close' icon

src/test/java/xyz/npgw/test/page/common/TableComponent.java, src/test/java/xyz/npgw/test/page/system/UserTableComponent.java, src/test/java/xyz/npgw/test/run/AcquirersPageTest.java
https://github.com/NPGW/npgw-ui-test/issues/557
=> ATC_11.000.10	Verify that Acquirer with status 'Active/Inactive' is displayed correctly in the list

src/test/java/xyz/npgw/test/page/TransactionsPage.java, src/test/java/xyz/npgw/test/run/TransactionsPageTest.java
[[ATC_06.017.04] Verify, that 'Reset filter' button change 'Currency' to default value ( ALL)](https://github.com/NPGW/npgw-ui-test/issues/567)
=> [ATC_06.017.04] Verify, that 'Reset filter' button change 'Currency' to default value ( ALL)

src/test/java/xyz/npgw/test/page/common/AlertComponent.java, src/test/java/xyz/npgw/test/page/system/CompaniesAndBusinessUnitsPage.java, src/test/java/xyz/npgw/test/run/AddAcquirerDialogTest.java, src/test/java/xyz/npgw/test/run/AddBusinessUnitTest.java, src/test/java/xyz/npgw/test/run/AddCompanyDialogTest.java, src/test/java/xyz/npgw/test/run/EditCompanyDialogTest.java, src/test/java/xyz/npgw/test/run/HeaderTest.java, src/test/java/xyz/npgw/test/run/TeamPageTest.java
Also #224 deleted since this check confirmed this other tests https://github.com/NPGW/npgw-ui-test/issues/246
=> Added asserts due to bug fix

src/test/java/xyz/npgw/test/page/DashboardPage.java, src/test/java/xyz/npgw/test/page/TransactionsPage.java, src/test/java/xyz/npgw/test/run/AddBusinessUnitTest.java, src/test/java/xyz/npgw/test/run/DashboardPageTest.java, src/test/java/xyz/npgw/test/run/EditBusinessUnitDialogTest.java, src/test/java/xyz/npgw/test/run/TeamPageTest.java, src/test/java/xyz/npgw/test/run/TransactionsPageTest.java
=> [ATC-06.005.00] The request to server contains all the information from the filter

src/test/java/xyz/npgw/test/page/dialog/user/AddUserDialog.java, src/test/java/xyz/npgw/test/page/dialog/user/UserDialog.java, src/test/java/xyz/npgw/test/run/TeamPageTest.java
=> [ATC-09.002.07] Adding a user with an existing email address results in an error message.

src/test/java/xyz/npgw/test/page/common/table/BaseTableComponent.java, src/test/java/xyz/npgw/test/run/TransactionsPageTest.java
=> [ATC-06.003.01] Filtering transactions by Card type displays only matching entries in the table.

src/test/java/xyz/npgw/test/page/ReportsPage.java, src/test/java/xyz/npgw/test/page/common/DateRangePickerComponent.java, src/test/java/xyz/npgw/test/run/ReportsPageTest.java
[[ATC_07.002.00] Reports > Verify that clicking the 'Reset filter' button resets all filters to their default state.](https://github.com/NPGW/npgw-ui-test/issues/653)
=> [ATC_07.002.00] Reports > Verify that clicking the 'Reset filter' button resets all filters to their default state.

src/test/java/xyz/npgw/test/page/common/table/TransactionsTableComponent.java, src/test/java/xyz/npgw/test/run/TransactionsPageTest.java
=> [ATC-06.000.02] Filtering transactions by Date range

src/test/java/xyz/npgw/test/page/common/SelectBusinessUnitComponent.java, src/test/java/xyz/npgw/test/run/TransactionsPageTest.java
[[ATC_06.017.02] Verify, that 'Reset filter' cleans 'Business Unit' field to empty](https://github.com/NPGW/npgw-ui-test/issues/701)
=> [ATC_06.017.02] Verify, that 'Reset filter' cleans 'Business Unit' field to emptyEd reset buisiness unit

src/test/java/xyz/npgw/test/common/Constants.java, src/test/java/xyz/npgw/test/common/base/BaseTest.java, src/test/java/xyz/npgw/test/common/util/ResponseUtils.java, src/test/java/xyz/npgw/test/page/LoginPage.java, src/test/java/xyz/npgw/test/page/common/SelectCompanyComponent.java, src/test/java/xyz/npgw/test/page/common/table/BaseTableComponent.java, src/test/java/xyz/npgw/test/page/common/table/BusinessUnitsTableComponent.java, src/test/java/xyz/npgw/test/page/dialog/merchant/DeleteBusinessUnitDialog.java, src/test/java/xyz/npgw/test/page/system/GatewayPage.java, src/test/java/xyz/npgw/test/run/DashboardPageTest.java, src/test/java/xyz/npgw/test/run/EditBusinessUnitDialogTest.java, src/test/java/xyz/npgw/test/run/GatewayPageTest.java
=> Delete business unit

src/test/java/xyz/npgw/test/run/TransactionsPageTest.java
[[ATC_06.018.03] ](https://github.com/NPGW/npgw-ui-test/issues/740)
=> [ATC_06.018.03] Verify, the Transaction detail dialog is closed after clicking on 'x' button"add testCloseXIcon

src/test/java/xyz/npgw/test/page/base/HeaderPage.java, src/test/java/xyz/npgw/test/run/AddBusinessUnitTest.java, src/test/java/xyz/npgw/test/run/CompaniesAndBusinessUnitsTest.java
testAddBusinessUnitEndToEndTest have testCompanyNameFieldDefaultState
and  testVerifyAddBusinessUnitButtonDefaultState asserts
testResetAppliedFiltermoved mooved from AddBusinessUnit to CompaniesAndBusinessUnitsTest
testAddNewMerchants have company type in BU name and assert repeat End to end test
testVerifyAvailabilityOfBusinessUnitButton is checking if buttons enable which does not make sense to me since we click on them in other tests?
=> Refactor Add BU

src/test/java/xyz/npgw/test/page/base/HeaderPage.java, src/test/java/xyz/npgw/test/page/common/SelectDateRangeComponent.java, src/test/java/xyz/npgw/test/page/system/CompaniesAndBusinessUnitsPage.java, src/test/java/xyz/npgw/test/page/system/GatewayPage.java, src/test/java/xyz/npgw/test/page/system/TeamPage.java, src/test/java/xyz/npgw/test/run/DashboardPageTest.java, src/test/java/xyz/npgw/test/run/TeamPageTest.java
summary is updating currently once in 24h at ...T00:00:00.000Z so we have to include the day before build too
=> Fix dashboard summary tests

src/test/java/xyz/npgw/test/page/common/table/BaseTableComponent.java, src/test/java/xyz/npgw/test/page/dialog/merchant/AddBusinessUnitDialog.java, src/test/java/xyz/npgw/test/page/dialog/merchant/BusinessUnitDialog.java, src/test/java/xyz/npgw/test/page/dialog/merchant/EditBusinessUnitDialog.java, src/test/java/xyz/npgw/test/run/EditBusinessUnitDialogTest.java
=> [ATC-10.008.06] Editing a business unit updates its name while preserving the same ID

src/test/java/xyz/npgw/test/page/dialog/acquirer/EditAcquirerDialog.java, src/test/java/xyz/npgw/test/page/system/AcquirersPage.java, src/test/java/xyz/npgw/test/run/EditAcquirerDialogTest.java
https://github.com/NPGW/npgw-ui-test/issues/239
=> ATC_11.006.01	Edit Acquirer and Verify Updated Data in the Table

src/test/java/xyz/npgw/test/page/common/table/TransactionsTableComponent.java, src/test/java/xyz/npgw/test/page/dialog/TransactionDetailsDialog.java, src/test/java/xyz/npgw/test/run/TransactionsPageTest.java
06.018.05 | Check that the 'Pending' occurs at most once in the Payment lifecycle section
06.018.06 | Verify: Statuses in the dialog header and lifecycle are the same
06.018.07 | Verify: The Payment lifecycle begins with 'INITIATED' and it occurs exactly once
=> [ATC_06.018.05] Transactions details | testPendingOccursAtMostOnceInLifecycle

src/test/java/xyz/npgw/test/page/common/table/TransactionsTableComponent.java, src/test/java/xyz/npgw/test/page/dialog/transactions/RefundTransactionDialog.java, src/test/java/xyz/npgw/test/page/dialog/transactions/TransactionDetailsDialog.java, src/test/java/xyz/npgw/test/run/TransactionDetailsTest.java, src/test/java/xyz/npgw/test/run/TransactionsTableTest.java
=> [ATC_06.019.01] All refundable transactions display correct refund dialog text and pre-filled refund amount.

src/test/java/xyz/npgw/test/page/common/MenuComponent.java, src/test/java/xyz/npgw/test/page/dialog/adjustment/AddAdjustmentDialog.java, src/test/java/xyz/npgw/test/page/system/TransactionManagementPage.java, src/test/java/xyz/npgw/test/run/TransactionManagementPageTest.java
https://github.com/NPGW/npgw-ui-test/issues/874
https://github.com/NPGW/npgw-ui-test/issues/873
=> A bit of test infrastructure for TransactionManagementPage

src/test/java/xyz/npgw/test/page/dialog/adjustment/AddAdjustmentDialog.java, src/test/java/xyz/npgw/test/run/TransactionManagementPageTest.java
https://github.com/NPGW/npgw-ui-test/issues/884
=> A small check for Adjustment Create button default state

src/test/java/xyz/npgw/test/page/common/table/GatewayTableComponent.java, src/test/java/xyz/npgw/test/page/dialog/gateway/AddMerchantAcquirerDialog.java, src/test/java/xyz/npgw/test/run/GatewayPageTest.java
refactoring [12.004.01] > add different sorting options
[[12.004.01] GW > Verify that entries can be sorted by Priority, Status, Acquirer name and Currencies](https://github.com/NPGW/npgw-ui-test/issues/864)
=> [12.004.01] GW > Verify that entries can be sorted by Priority, Status, Acquirer name and Currencies

src/test/java/xyz/npgw/test/run/TeamPageTest.java
=> [ATC_10.009.01] Verify that business unit cannot be deleted if there are users associated with it

src/test/java/xyz/npgw/test/page/dialog/BaseDialog.java, src/test/java/xyz/npgw/test/run/FraudControlTest.java
Fraud Control Cancel features
close #920
=> Fraud Control Cancel features #920

src/test/java/xyz/npgw/test/page/dialog/control/FraudControlDialog.java, src/test/java/xyz/npgw/test/run/TransactionsPageTest.java
=> Refactor #181 and FraudControlDialog

src/test/java/xyz/npgw/test/page/common/table/FraudBusinessUnitControlsTableComponent.java, src/test/java/xyz/npgw/test/run/FraudControlTest.java
https://github.com/NPGW/npgw-ui-test/issues/949
https://github.com/NPGW/npgw-ui-test/issues/950
=> Delete Active Fraud Controls both: added and no added to Business unit

src/test/java/xyz/npgw/test/run/FraudControlTest.java
https://github.com/NPGW/npgw-ui-test/issues/955
=> Change Fraud Controls activity not added to Business unit

pom.xml, src/test/java/xyz/npgw/test/common/entity/Transaction.java, src/test/java/xyz/npgw/test/page/TransactionsPage.java, src/test/java/xyz/npgw/test/run/TransactionsTableTest.java
=> [ATC_06.006.03]  The transaction table data on the UI matches the exported PDF file data.

src/test/java/xyz/npgw/test/page/common/table/BusinessUnitControlsTableComponent.java, src/test/java/xyz/npgw/test/run/FraudControlTest.java
https://github.com/NPGW/npgw-ui-test/issues/960
=> Change fraud control priority

src/test/java/xyz/npgw/test/page/TransactionsPage.java, src/test/java/xyz/npgw/test/run/FraudControlTest.java
[ Edit Fraud Control](https://github.com/NPGW/npgw-ui-test/issues/986)
=> [ATC _13.000.02] Edit Fraud Control

src/test/java/xyz/npgw/test/page/common/table/ControlsTableComponent.java, src/test/java/xyz/npgw/test/run/FraudControlTest.java
https://github.com/NPGW/npgw-ui-test/issues/1001
=> Hovers for available actions check on Control table

src/test/java/xyz/npgw/test/page/system/FraudControlPage.java, src/test/java/xyz/npgw/test/run/FraudControlTest.java
=> [ATC_13.009.00] Fraud control | 'Reset filter' clears selected options

pom.xml, src/test/java/xyz/npgw/test/page/TransactionsPage.java, src/test/java/xyz/npgw/test/page/common/table/TransactionsTableComponent.java, src/test/java/xyz/npgw/test/run/TransactionsTableTest.java
=> [ATC_06.006.04] The transaction table data on the UI matches the exported Excel file data.

src/test/java/xyz/npgw/test/run/DashboardPageTest.java, src/test/java/xyz/npgw/test/run/FraudControlTest.java
[[13.002.00] System | Fraud control | Entries sorting in business unit control table](https://github.com/NPGW/npgw-ui-test/issues/1013)
=> [13.002.00] System | Fraud control | Entries sorting in business unit control table

src/test/java/xyz/npgw/test/page/dialog/BaseDialog.java, src/test/java/xyz/npgw/test/run/FraudControlTest.java
https://github.com/NPGW/npgw-ui-test/issues/1143
=> Warning message text change activity on Control table

src/test/java/xyz/npgw/test/page/component/table/UsersTableComponent.java, src/test/java/xyz/npgw/test/page/system/BaseTeamPage.java, src/test/java/xyz/npgw/test/page/system/SuperTeamPage.java, src/test/java/xyz/npgw/test/run/FraudControlTest.java, src/test/java/xyz/npgw/test/run/TeamPageTest.java
[[ATC_09.005.01]Contents of Tooltips, that appear after hovering on the icon-buttons, are correct](https://github.com/NPGW/npgw-ui-test/issues/1161)
=> [ATC_09.005.01]Contents of Tooltips, that appear after hovering on the icon-buttons, are correct

src/test/java/xyz/npgw/test/page/component/table/AcquirersTableComponent.java, src/test/java/xyz/npgw/test/page/dialog/acquirer/ActivateGroupGatewayItemsDialog.java, src/test/java/xyz/npgw/test/page/dialog/acquirer/DeactivateGroupGatewayItemsDialog.java, src/test/java/xyz/npgw/test/run/AcquirersPageTest.java, src/test/java/xyz/npgw/test/run/FraudControlTest.java
=> [ATC_11.009.00] Verify that gateway Acquirer MID can be deactivated and then activated via bulk actions

src/test/java/xyz/npgw/test/run/AcquirersPageTest.java, src/test/java/xyz/npgw/test/run/FraudControlTest.java, src/test/java/xyz/npgw/test/run/GatewayPageTest.java
https://github.com/NPGW/npgw-ui-test/issues/1185
=> Delete control dialog text content

src/test/java/xyz/npgw/test/run/FraudControlTest.java
https://github.com/NPGW/npgw-ui-test/issues/1197
=> 'Delete business unit control' dialog

src/test/java/xyz/npgw/test/run/FraudControlTest.java
https://github.com/NPGW/npgw-ui-test/issues/1201
=> Add already added Fraud Control to Business Unit

src/test/java/xyz/npgw/test/page/system/BaseTeamPage.java, src/test/java/xyz/npgw/test/run/AdminTeamPageTest.java, src/test/java/xyz/npgw/test/run/TeamPageTest.java
[[ATC_09.004.01>]User can choose the view of the Transactions Table (normal or condensed) in Settings dropdown panel](https://github.com/NPGW/npgw-ui-test/issues/1210)
=> [ATC_09.004.01>]User can choose the view of the Transactions Table (normal or condensed) in Settings dropdown panel
